#LTE-MAC-test/Debug/LTE-MAC-test.exe: 
#	build-tests.bat

# Always rebuild as it is quick
test: 
	./build-tests.bat
	LTE-MAC-test/Win32/Debug/LTE-MAC-test.exe

clean: 
	rm -f LTE-MAC-test/Win32/Debug/LTE-MAC-test.exe
